config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root                'static_pages#home'
  get   'help'   =>   'static_pages#help'
  get   'event'  =>   'static_pages#event'
  
  
  # Directing the user after login
  authenticated :user do
    root :to => 'static_pages#event', as: :authenticated_root
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
    belongs_to :user
    validate :start_time_doesnt_overlap
  
    def start_time_doesnt_overlap
      if self.class.where("start_time >= ? AND start_time <= ? OR
        start_time <= ? AND start_time >= ?", start_time, start_time + 2.hours, 
        start_time, start_time - 2.hours).any?
        errors.add(:start_time, "overlaps with another funeral")
      end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meetings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Funeral was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Funeral was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Funeral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'forecast'
  
  def home
  end

  def help
  end
  
  def event
    @meetings = Meeting.all
    @forecast = Forecast.fetch
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Cat funeral app</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",   help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Cat funeral app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "Funerals", event_path %></li>
          <li><%= link_to "Help",     help_path %></li>
          <li><%= link_to "Log out",  destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "Help",     help_path %></li>
          <li><%= link_to "Log in",   new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Cat funeral</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this funeral from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Funerals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Funeral', new_meeting_path %>

<br>

<%= link_to "Back to calendar", event_path %>

app/views/meetings/new.html.erb
<h1>New Funeral</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/static_pages/event.html.erb
<% provide(:title, "Event") %>
<h1>Funeral</h1>


<p><%= link_to "> Create new cat funeral event", new_meeting_path %></p>
<p><%= link_to "> Edit cat funeral event", meetings_path %></p>
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %> 
  
  <% @forecast["list"].each do |list| %>
    <% if Time.at(list["dt"]).to_datetime.strftime("%y-%m-%e") == date.to_datetime.strftime("%y-%m-%e") %> 
      <% list["weather"].each do |weather| %> 
        <%= weather["description"] %> <br />
      <% end %>
    <% end %>
  <% end %>
  
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, edit_meeting_path(meeting) %> 
      <%= meeting.start_time.strftime("%H:%M") %>
    </div>
  <% end %>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>1) Login/register</p>
<p>2) Pick a free slot</p>
<p>3) Say a last goodbye to your kitten</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home</h1>
<p>This is home page</p>


<div class="center jumbotron">
  <h1>Welcome to Cat funeral app</h1>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("logo.png", alt: "Cat funeral logo"), '#' %>